### ISSUE TITLE
Message Parsing Fails with Japanese Characters

### ISSUE THREAD

**Issue by blackberryoctopus** [caio1982/Lost-Photos-Found#5]
@caio1982 @cmatsuoka 

I just ran the script and did a mini investigation of the issue, but since Im not a python expert someone with more experience can probably solve more easily. 

I believe the issue is related to the Japanese character/weird string encoding "\xe3?==?utf-8?Q?"  ( present in the subject of the email )

I found the email in question by adding a print statement to the function _charset_decoder() in the utils.py at line 31

Here is the subject string: 
"Fwd: 黒田征太郎氏、from Nina"

Here is the error output from the script:
`[('Fwd: \xe9\xbb\x92\xe7\x94\xb0\xe5\xbe\x81\xe5\xa4\xaa\xe9\x83\x8e\xe6\xb0\x8f\xe3?==?utf-8?Q?\x80\x81from Nina', 'utf-8')]
Traceback (most recent call last):
  File "./lpf.py", line 26, in <module>
    imap.lostphotosfound()
  File "/Users/gsogorka/Documents/Code/Lost-Photos-Found/lostphotosfound/server.py", line 150, in lostphotosfound
    header_subject = _charset_decoder(mail['Subject'])
  File "/Users/gsogorka/Documents/Code/Lost-Photos-Found/lostphotosfound/utils.py", line 46, in _charset_decoder
    header = header[0][0].decode(header[0][1]).encode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 23: invalid continuation byte`

**Comment by cmatsuoka** [comment]
Possibly a generalization of 6b07fe6 could help here. We could add a function to utils to deal with encoding, add the workaround there and use it instead of .encode('utf-8').

**Comment by caio1982** [comment]
Can you @blackberryoctopus and @jhurliman try the latest code please? I am not getting errors myself anymore, thanks to changes @cmatsuoka landed.

**Comment by jhurliman** [comment]
```
Traceback (most recent call last):
  File "./lpf.py", line 40, in <module>
    imap.lostphotosfound()
  File "/Volumes/Storage/jhurliman/Code/Lost-Photos-Found/lostphotosfound/server.py", line 264, in lostphotosfound
    header_subject = _charset_decoder(mail['Subject'])
  File "/Volumes/Storage/jhurliman/Code/Lost-Photos-Found/lostphotosfound/utils.py", line 42, in _charset_decoder
    header = header[0][0].decode(header[0][1]).encode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 76: invalid continuation byte
```
